name = "ASAProject"
uuid = "72d98804-f532-425e-9ec7-811ea8f51410"
authors = ["Leandro Prudente"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuadraticModels = "f468eda6-eac5-11e8-05a5-ff9e497bcd19"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
RipQP = "1e40b3f8-35eb-4cd8-8edd-3e515bb9de08"

[compat]
LinearAlgebra = "1.11.0"
Printf = "1.11.0"
QuadraticModels = "0.9.14"
Random = "1.11.0"
RipQP = "0.7.0"
