[deps]
MOProblems = "a5b80fa4-7d73-4f2e-b7b1-8d4a9c5c7c4d"
QPSReader = "10f199a5-22af-520b-b891-7ce84a7b1bd0"
QuadraticModels = "f468eda6-eac5-11e8-05a5-ff9e497bcd19"
RipQP = "1e40b3f8-35eb-4cd8-8edd-3e515bb9de08"
SparseMatricesCOO = "fa32481b-f100-4b48-8dc8-c62f61b13870"
