name = "MAMBOProject"
uuid = "72d98804-f532-425e-9ec7-811ea8f51410"
version = "0.1.0"
authors = ["Leandro Prudente"]

[deps]
BenchmarkProfiles = "ecbce9bc-3e5e-569d-9e29-55181f61f8d0"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
Metaheuristics = "bcdb8e00-2c21-11e9-3065-2b553b22f898"
MetricsRel = "9f5c2b7e-6f1d-4a5e-bc9a-4c6c0c7a9d31"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuadraticModels = "f468eda6-eac5-11e8-05a5-ff9e497bcd19"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
RipQP = "1e40b3f8-35eb-4cd8-8edd-3e515bb9de08"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"

[compat]
BenchmarkProfiles = "0.4.6"
Glob = "1.3.1"
LinearAlgebra = "1.11.0"
LinearOperators = "2.11.0"
Metaheuristics = "3.4.1"
Plots = "1.41.2"
Printf = "1.11.0"
QuadraticModels = "0.9.14"
Random = "1.11.0"
RipQP = "0.7.0"
TikzPictures = "3.2.0"
