name = "MetricsRel"
uuid = "9f5c2b7e-6f1d-4a5e-bc9a-4c6c0c7a9d31"
version = "0.1.0"
authors = ["Leandro Prudente"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Metaheuristics = "bcdb8e00-2c21-11e9-3065-2b553b22f898"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
LinearAlgebra = "1.12.0"
Metaheuristics = "3.4.1"
Statistics = "1.11.1"
